application:
  actions: actions
  runtimeManifest:
    packages:
      toeled:
        license: Apache-2.0
        actions:
          qce-cert-lookup:
            function: actions/qce-cert-lookup/index.js
            web: 'yes'
            runtime: nodejs:22
            limits:
              memory: 256
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              final: true
